pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        def nuboHomeSdkRepo = System.getenv("NUBO_HOME_SDK_REPO")
        if (nuboHomeSdkRepo != null && !nuboHomeSdkRepo.trim().isEmpty()) {
            maven { url = uri(nuboHomeSdkRepo) }
        }
        google()
        mavenCentral()
    }
}

rootProject.name = "NuboAndroid"
include(":app")
